name: Deploy my website
on:
  push:
    branches:    
      # Push events on master branch
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Put steps here to build your site, deploy it to a service, etc.

    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        # Zone is required by both authentication methods
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}

        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        PURGE_URLS: '["https://SUBDOMAIN.jerma.io", "https://SUBDOMAIN.jerma.io/styles.css", "https://SUBDOMAIN.jerma.io/scripts.js"]'
